using System;
using System.Diagnostics;
using System.Linq;
using Certes;
using Certes.Acme;
using Certes.Pkcs;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace nilnul._crypt_._TEST_.ca_.letsCrypt.acc.order.csr
{
	[TestClass]
	public class UnitTest1
	{
		[TestMethod]
		public void TestMethod1()
		{
			/*
			 C-xizY0evOS_ux3ph3rCdLZl1L1Ku9J8ghpuz9kxWow
			 */

			var pemKey = @"-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIPRzqDEjeyVXk+0EHfzjZ5pLHla2LI7hL3w4rLofM0mLoAoGCCqGSM49
AwEHoUQDQgAEbJMi61CDkLtKdec6OkbXibhUCNrLr0Yv9lNXztfysEw1SfHtf07O
Z3Q+RA0xoke6dkNy4h+zgJ5P7uWjoVZakg==
-----END EC PRIVATE KEY-----
";
			// Load the saved account key
			var accountKey = KeyFactory.FromPem(pemKey);
			var acme = new AcmeContext(WellKnownServers.LetsEncryptStagingV2, accountKey);
			var account = acme.Account().Result;



			/*	Order
	Place a wildcard certificate order(DNS validation is required for wildcard certificates)
	*/

			const string domain = "nilnul.com";

			var domainFinal = $"*.{domain}";

			//var domainUri = new Uri(domainFinal); https://acme-staging-v02.api.letsencrypt.org/acme/order/11484349/59946388

			var location = new Uri("https://acme-staging-v02.api.letsencrypt.org/acme/order/11484349/59946388");

			var order = acme.Order(location);
			//var order = account.Orders().Result.Orders().Result.FirstOrDefault();//  acme.Order(domainUri);//.Result;
			var csr = @"-----BEGIN NEW CERTIFICATE REQUEST-----
MIIEYTCCA0kCAQAwbjELMAkGA1UEBhMCQ04xDjAMBgNVBAgMBUh1YmVpMQ4wDAYD
VQQHDAVXdWhhbjETMBEGA1UECgwKbmlsbnVsLmNvbTETMBEGA1UECwwKbmlsbnVs
LmNvbTEVMBMGA1UEAwwMKi5uaWxudWwuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAvWlrz373F5wcH18YwAtK8YkOfVbazZNpdL8kUpZdNPif+qdj
NHYmiMcPhkcgeQb7t3iKnjn9QyXNLyVwEYq5tpb3xAbwLukhwrdl2+eoeg6yxXaJ
x9BiEH9+NGAybcrBhcPbVxvRWmgA72p2iw+XUBgej4jY8LrwRzoG3+rO9SQbjeYr
WHxrj6CslB4l4XsoFyFZsSs+33SSdL8mVLUjq+K+j0xaGqVuugb4Fcm+0XqAgvki
ItPCJiJiBiy9jMqEF6C9ODZSStcFnUbEuyeZPezf/OGdJ9hhcMoDPldnnLzpUizQ
Hb5I4V+vqmnBig6b2JyrLeScUNdYHbIV1MNUQQIDAQABoIIBrDAaBgorBgEEAYI3
DQIDMQwWCjYuMC42MDAyLjIwSAYJKwYBBAGCNxUUMTswOQIBBQwXV0gtY2VydC5X
aW5Ib3N0Q29ycC5jb20MEVdJTkhPU1Rcc21hcnRjb2RlDAh3M3dwLmV4ZTByBgor
BgEEAYI3DQICMWQwYgIBAR5aAE0AaQBjAHIAbwBzAG8AZgB0ACAAUgBTAEEAIABT
AEMAaABhAG4AbgBlAGwAIABDAHIAeQBwAHQAbwBnAHIAYQBwAGgAaQBjACAAUABy
AG8AdgBpAGQAZQByAwEAMIHPBgkqhkiG9w0BCQ4xgcEwgb4wDgYDVR0PAQH/BAQD
AgTwMBMGA1UdJQQMMAoGCCsGAQUFBwMBMHgGCSqGSIb3DQEJDwRrMGkwDgYIKoZI
hvcNAwICAgCAMA4GCCqGSIb3DQMEAgIAgDALBglghkgBZQMEASowCwYJYIZIAWUD
BAEtMAsGCWCGSAFlAwQBAjALBglghkgBZQMEAQUwBwYFKw4DAgcwCgYIKoZIhvcN
AwcwHQYDVR0OBBYEFAPs+HIpsRAj57zc3MwvRZLLtovzMA0GCSqGSIb3DQEBBQUA
A4IBAQCWdDyR4Rut8mJtRl+1+pcafItbiIayL/uu36dHVFpOmNxPRWIMqecv7YVM
XqTt4nMbSkQtweijmalzR80SCLrnmaxwtFTqAH+Gtx1ntTUZ9InuA+e2faRthU81
onTw/a25w3MBsTSHWgeAbwNT/X2rTQZk/2EkqwcEdn4/AzMEVlXV9XpfKmq953Ws
Wm5SRAimmLUZWG2ompH7M9gj5yFvhVkfB421L+h1EjOCeOdJu8LG8TuPU235PZCj
aEMoeEJdqlXZhwGcgHe5vyyIg+eApW0nqSV3Rln8xjl11xJJARKuW5BRmEhKABEh
g0aEHsHx5qQLmrFHJeQDmIh/8jCa
-----END NEW CERTIFICATE REQUEST-----";
			var csrWithNoBounds = @"MIIEYTCCA0kCAQAwbjELMAkGA1UEBhMCQ04xDjAMBgNVBAgMBUh1YmVpMQ4wDAYD
VQQHDAVXdWhhbjETMBEGA1UECgwKbmlsbnVsLmNvbTETMBEGA1UECwwKbmlsbnVs
LmNvbTEVMBMGA1UEAwwMKi5uaWxudWwuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAvWlrz373F5wcH18YwAtK8YkOfVbazZNpdL8kUpZdNPif+qdj
NHYmiMcPhkcgeQb7t3iKnjn9QyXNLyVwEYq5tpb3xAbwLukhwrdl2+eoeg6yxXaJ
x9BiEH9+NGAybcrBhcPbVxvRWmgA72p2iw+XUBgej4jY8LrwRzoG3+rO9SQbjeYr
WHxrj6CslB4l4XsoFyFZsSs+33SSdL8mVLUjq+K+j0xaGqVuugb4Fcm+0XqAgvki
ItPCJiJiBiy9jMqEF6C9ODZSStcFnUbEuyeZPezf/OGdJ9hhcMoDPldnnLzpUizQ
Hb5I4V+vqmnBig6b2JyrLeScUNdYHbIV1MNUQQIDAQABoIIBrDAaBgorBgEEAYI3
DQIDMQwWCjYuMC42MDAyLjIwSAYJKwYBBAGCNxUUMTswOQIBBQwXV0gtY2VydC5X
aW5Ib3N0Q29ycC5jb20MEVdJTkhPU1Rcc21hcnRjb2RlDAh3M3dwLmV4ZTByBgor
BgEEAYI3DQICMWQwYgIBAR5aAE0AaQBjAHIAbwBzAG8AZgB0ACAAUgBTAEEAIABT
AEMAaABhAG4AbgBlAGwAIABDAHIAeQBwAHQAbwBnAHIAYQBwAGgAaQBjACAAUABy
AG8AdgBpAGQAZQByAwEAMIHPBgkqhkiG9w0BCQ4xgcEwgb4wDgYDVR0PAQH/BAQD
AgTwMBMGA1UdJQQMMAoGCCsGAQUFBwMBMHgGCSqGSIb3DQEJDwRrMGkwDgYIKoZI
hvcNAwICAgCAMA4GCCqGSIb3DQMEAgIAgDALBglghkgBZQMEASowCwYJYIZIAWUD
BAEtMAsGCWCGSAFlAwQBAjALBglghkgBZQMEAQUwBwYFKw4DAgcwCgYIKoZIhvcN
AwcwHQYDVR0OBBYEFAPs+HIpsRAj57zc3MwvRZLLtovzMA0GCSqGSIb3DQEBBQUA
A4IBAQCWdDyR4Rut8mJtRl+1+pcafItbiIayL/uu36dHVFpOmNxPRWIMqecv7YVM
XqTt4nMbSkQtweijmalzR80SCLrnmaxwtFTqAH+Gtx1ntTUZ9InuA+e2faRthU81
onTw/a25w3MBsTSHWgeAbwNT/X2rTQZk/2EkqwcEdn4/AzMEVlXV9XpfKmq953Ws
Wm5SRAimmLUZWG2ompH7M9gj5yFvhVkfB421L+h1EjOCeOdJu8LG8TuPU235PZCj
aEMoeEJdqlXZhwGcgHe5vyyIg+eApW0nqSV3Rln8xjl11xJJARKuW5BRmEhKABEh
g0aEHsHx5qQLmrFHJeQDmIh/8jCa";
			var csrBuilder = Certes.Jws.JwsConvert.FromBase64String(csrWithNoBounds.Replace("\n","").Replace("\r",""));
			
			
			order.Finalize(csrBuilder);


			var certChain = order.Download().Result;
			var pemOut=certChain.ToPem();
			Debug.WriteLine(pemOut);


		}
	}
}

/*
 * 
 * Test Name:	TestMethod1
Test Outcome:	Passed
Result StandardOutput:	
Debug Trace:
-----BEGIN CERTIFICATE-----
MIIFMTCCBBmgAwIBAgITAPqmPTzBUGgsGU47T0IQdhAFMjANBgkqhkiG9w0BAQsF
ADAiMSAwHgYDVQQDDBdGYWtlIExFIEludGVybWVkaWF0ZSBYMTAeFw0xOTExMDUw
NjU0MjNaFw0yMDAyMDMwNjU0MjNaMBcxFTATBgNVBAMMDCoubmlsbnVsLmNvbTCC
ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL1pa89+9xecHB9fGMALSvGJ
Dn1W2s2TaXS/JFKWXTT4n/qnYzR2JojHD4ZHIHkG+7d4ip45/UMlzS8lcBGKubaW
98QG8C7pIcK3ZdvnqHoOssV2icfQYhB/fjRgMm3KwYXD21cb0VpoAO9qdosPl1AY
Ho+I2PC68Ec6Bt/qzvUkG43mK1h8a4+grJQeJeF7KBchWbErPt90knS/JlS1I6vi
vo9MWhqlbroG+BXJvtF6gIL5IiLTwiYiYgYsvYzKhBegvTg2UkrXBZ1GxLsnmT3s
3/zhnSfYYXDKAz5XZ5y86VIs0B2+SOFfr6ppwYoOm9icqy3knFDXWB2yFdTDVEEC
AwEAAaOCAmkwggJlMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcD
AQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUA+z4cimxECPnvNzc
zC9Fksu2i/MwHwYDVR0jBBgwFoAUwMwDRrlYIMxccnDz4S7LIKb1aDowdwYIKwYB
BQUHAQEEazBpMDIGCCsGAQUFBzABhiZodHRwOi8vb2NzcC5zdGctaW50LXgxLmxl
dHNlbmNyeXB0Lm9yZzAzBggrBgEFBQcwAoYnaHR0cDovL2NlcnQuc3RnLWludC14
MS5sZXRzZW5jcnlwdC5vcmcvMBcGA1UdEQQQMA6CDCoubmlsbnVsLmNvbTBMBgNV
HSAERTBDMAgGBmeBDAECATA3BgsrBgEEAYLfEwEBATAoMCYGCCsGAQUFBwIBFhpo
dHRwOi8vY3BzLmxldHNlbmNyeXB0Lm9yZzCCAQQGCisGAQQB1nkCBAIEgfUEgfIA
8AB1AN2ZNPyl5ySAyVZofYE0mQhJskn3tWnYx7yrP1zB825kAAABbjqOvucAAAQD
AEYwRAIgNKuUH+SATthT51qwz0sPT0Ttz1a/wz3hNZgSm6MIu9kCIF2gLcK/b1Wu
MDjS9JTSyL9TxdZeZZ/u+rsFb4YHoUDjAHcAsMyD5aX5fWuvfAnMKEkEhyrH6IsT
LGNQt8b9JuFsbHcAAAFuOo6+6wAABAMASDBGAiEA6oufgeObUrjDVI2T3IkQOWUn
IGseaJhIfe9eDrxVG3MCIQDDkt8q299we5tsRfWWu1MgnotHKeCL4MBjyVAGv1R+
7zANBgkqhkiG9w0BAQsFAAOCAQEAMmtR5N2Nb3w2uG2fIcmuzZuKmnykE0BTere+
ajTsKnTwDM9Svapq3RfPu26z5Oxkgd8qtrnedp1qSPI3f47obufwAfM38WlFzCra
9SM0lEq+uGNk8sqYIBPKowu1fwV3yaWIoFnFOENzbxe9ax/Ceopk5vf5uxuDEBl2
/abFWkbfySdef5UmqAAZIU9X8GtokKmwFn3+rDPXwjaKOGOswwMc0dTXnJpAj+WR
udQSNvciko3gLUo+cSwyAVK8sUGTbZn/usxJA8wfaxvEZUHUbc6WrbUC325oT7DT
1kr6Cqiz+dosOsMRkca61avpIceNgSFI3tsuo2iwSAnCJFKPBw==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEqzCCApOgAwIBAgIRAIvhKg5ZRO08VGQx8JdhT+UwDQYJKoZIhvcNAQELBQAw
GjEYMBYGA1UEAwwPRmFrZSBMRSBSb290IFgxMB4XDTE2MDUyMzIyMDc1OVoXDTM2
MDUyMzIyMDc1OVowIjEgMB4GA1UEAwwXRmFrZSBMRSBJbnRlcm1lZGlhdGUgWDEw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDtWKySDn7rWZc5ggjz3ZB0
8jO4xti3uzINfD5sQ7Lj7hzetUT+wQob+iXSZkhnvx+IvdbXF5/yt8aWPpUKnPym
oLxsYiI5gQBLxNDzIec0OIaflWqAr29m7J8+NNtApEN8nZFnf3bhehZW7AxmS1m0
ZnSsdHw0Fw+bgixPg2MQ9k9oefFeqa+7Kqdlz5bbrUYV2volxhDFtnI4Mh8BiWCN
xDH1Hizq+GKCcHsinDZWurCqder/afJBnQs+SBSL6MVApHt+d35zjBD92fO2Je56
dhMfzCgOKXeJ340WhW3TjD1zqLZXeaCyUNRnfOmWZV8nEhtHOFbUCU7r/KkjMZO9
AgMBAAGjgeMwgeAwDgYDVR0PAQH/BAQDAgGGMBIGA1UdEwEB/wQIMAYBAf8CAQAw
HQYDVR0OBBYEFMDMA0a5WCDMXHJw8+EuyyCm9Wg6MHoGCCsGAQUFBwEBBG4wbDA0
BggrBgEFBQcwAYYoaHR0cDovL29jc3Auc3RnLXJvb3QteDEubGV0c2VuY3J5cHQu
b3JnLzA0BggrBgEFBQcwAoYoaHR0cDovL2NlcnQuc3RnLXJvb3QteDEubGV0c2Vu
Y3J5cHQub3JnLzAfBgNVHSMEGDAWgBTBJnSkikSg5vogKNhcI5pFiBh54DANBgkq
hkiG9w0BAQsFAAOCAgEABYSu4Il+fI0MYU42OTmEj+1HqQ5DvyAeyCA6sGuZdwjF
UGeVOv3NnLyfofuUOjEbY5irFCDtnv+0ckukUZN9lz4Q2YjWGUpW4TTu3ieTsaC9
AFvCSgNHJyWSVtWvB5XDxsqawl1KzHzzwr132bF2rtGtazSqVqK9E07sGHMCf+zp
DQVDVVGtqZPHwX3KqUtefE621b8RI6VCl4oD30Olf8pjuzG4JKBFRFclzLRjo/h7
IkkfjZ8wDa7faOjVXx6n+eUQ29cIMCzr8/rNWHS9pYGGQKJiY2xmVC9h12H99Xyf
zWE9vb5zKP3MVG6neX1hSdo7PEAb9fqRhHkqVsqUvJlIRmvXvVKTwNCP3eCjRCCI
PTAvjV+4ni786iXwwFYNz8l3PmPLCyQXWGohnJ8iBm+5nk7O2ynaPVW0U2W+pt2w
SVuvdDM5zGv2f9ltNWUiYZHJ1mmO97jSY/6YfdOUH66iRtQtDkHBRdkNBsMbD+Em
2TgBldtHNSJBfB3pm9FblgOcJ0FSWcUDWJ7vO0+NTXlgrRofRT6pVywzxVo6dND0
WzYlTWeUVsO40xJqhgUQRER9YLOLxJ0O6C8i0xFxAMKOtSdodMB3RIwt7RFQ0uyt
n5Z5MqkYhlMI3J1tPRTp1nEt9fyGspBOO05gi148Qasp+3N+svqKomoQglNoAxU=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFATCCAumgAwIBAgIRAKc9ZKBASymy5TLOEp57N98wDQYJKoZIhvcNAQELBQAw
GjEYMBYGA1UEAwwPRmFrZSBMRSBSb290IFgxMB4XDTE2MDMyMzIyNTM0NloXDTM2
MDMyMzIyNTM0NlowGjEYMBYGA1UEAwwPRmFrZSBMRSBSb290IFgxMIICIjANBgkq
hkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA+pYHvQw5iU3v2b3iNuYNKYgsWD6KU7aJ
diddtZQxSWYzUI3U0I1UsRPTxnhTifs/M9NW4ZlV13ZfB7APwC8oqKOIiwo7IwlP
xg0VKgyz+kT8RJfYr66PPIYP0fpTeu42LpMJ+CKo9sbpgVNDZN2z/qiXrRNX/VtG
TkPV7a44fZ5bHHVruAxvDnylpQxJobtCBWlJSsbIRGFHMc2z88eUz9NmIOWUKGGj
EmP76x8OfRHpIpuxRSCjn0+i9+hR2siIOpcMOGd+40uVJxbRRP5ZXnUFa2fF5FWd
O0u0RPI8HON0ovhrwPJY+4eWKkQzyC611oLPYGQ4EbifRsTsCxUZqyUuStGyp8oa
aoSKfF6X0+KzGgwwnrjRTUpIl19A92KR0Noo6h622OX+4sZiO/JQdkuX5w/HupK0
A0M0WSMCvU6GOhjGotmh2VTEJwHHY4+TUk0iQYRtv1crONklyZoAQPD76hCrC8Cr
IbgsZLfTMC8TWUoMbyUDgvgYkHKMoPm0VGVVuwpRKJxv7+2wXO+pivrrUl2Q9fPe
Kk055nJLMV9yPUdig8othUKrRfSxli946AEV1eEOhxddfEwBE3Lt2xn0hhiIedbb
Ftf/5kEWFZkXyUmMJK8Ra76Kus2ABueUVEcZ48hrRr1Hf1N9n59VbTUaXgeiZA50
qXf2bymE6F8CAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMB
Af8wHQYDVR0OBBYEFMEmdKSKRKDm+iAo2FwjmkWIGHngMA0GCSqGSIb3DQEBCwUA
A4ICAQBCPw74M9X/Xx04K1VAES3ypgQYH5bf9FXVDrwhRFSVckria/7dMzoF5wln
uq9NGsjkkkDg17AohcQdr8alH4LvPdxpKr3BjpvEcmbqF8xH+MbbeUEnmbSfLI8H
sefuhXF9AF/9iYvpVNC8FmJ0OhiVv13VgMQw0CRKkbtjZBf8xaEhq/YqxWVsgOjm
dm5CAQ2X0aX7502x8wYRgMnZhA5goC1zVWBVAi8yhhmlhhoDUfg17cXkmaJC5pDd
oenZ9NVhW8eDb03MFCrWNvIh89DDeCGWuWfDltDq0n3owyL0IeSn7RfpSclpxVmV
/53jkYjwIgxIG7Gsv0LKMbsf6QdBcTjhvfZyMIpBRkTe3zuHd2feKzY9lEkbRvRQ
zbh4Ps5YBnG6CKJPTbe2hfi3nhnw/MyEmF3zb0hzvLWNrR9XW3ibb2oL3424XOwc
VjrTSCLzO9Rv6s5wi03qoWvKAQQAElqTYRHhynJ3w6wuvKYF5zcZF3MDnrVGLbh1
Q9ePRFBCiXOQ6wPLoUhrrbZ8LpFUFYDXHMtYM7P9sc9IAWoONXREJaO08zgFtMp4
8iyIYUyQAbsvx8oD2M8kRvrIRSrRJSl6L957b4AFiLIQ/GgV2curs0jje7Edx34c
idWw1VrejtwclobqNMVtG3EiPUIpJGpbMcJgbiLSmKkrvQtGng==
-----END CERTIFICATE-----

	*/